server:
  port: 8082

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/course_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      uri: http://config-service:8888