server:
  port: 8761

spring:
  application:
    name: discoveryService
  security:
    user:
      name: adminDisc
      password: adminDisc

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  dashboard:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always