server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:testresourcedb?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Schools_Management/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/Schools_Management
          authorities-claim-name: realm_access.roles
          authority-prefix: ROLE_
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


# Document service settings
document:
  service:
    url: ${DOCUMENT_SERVICE_URL:http://localhost:8086}

AuthService:
  url: ${USER_MANAGEMENT_URL:http://localhost:8081}

keycloak:
  auth-server-url: http://localhost:8080
  realm: Schools_Management
  domain: http://localhost:8080
  client-id: school-management
  client-uuid: e737045f-f7f1-4b1e-83f3-1aa71425b9f3
  webhook-secret: Gq+zAzDljAtSWKC0gD9i8azCYAcXqUB3gsuOo4x+bDo=
  issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  group:
    teacher-id: cb149d80-7b12-49d0-ac88-3032d0bb565b
    admin-id: 54f5c789-c9ba-426a-8a8e-67189b13304e
#  #  admin-username: useradmin
#  #  admin-password: admin
#  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
#  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

application:
  frontend-url: http://localhost:3000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.auth: DEBUG
    org.springframework.security.oauth2.server.resource.authentication: TRACE